// <auto-generated />
namespace Question2.AshutoshNayak.eClerx.ModuleTest_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BookDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281030245_BookDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
